app/base/models.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask_login import UserMixin
from sqlalchemy import Binary, Column, Integer, String

from app import db, login_manager

from app.base.util import hash_pass

class User(db.Model, UserMixin):

    __tablename__ = 'User'

    id = Column(Integer, primary_key=True)
    username = Column(String, unique=True)
    email = Column(String, unique=True)
    password = Column(Binary)

    def __init__(self, **kwargs):
        for property, value in kwargs.items():
            # depending on whether value is an iterable or not, we must
            # unpack it's value (when **kwargs is request.form, some values
            # will be a 1-element list)
            if hasattr(value, '__iter__') and not isinstance(value, str):
                # the ,= unpack of a singleton fails PEP8 (travis flake8 test)
                value = value[0]

            if property == 'password':
                value = hash_pass( value ) # we need bytes here (not plain str)
                
            setattr(self, property, value)

    def __repr__(self):
        return str(self.username)


@login_manager.user_loader
def user_loader(id):
    return User.query.filter_by(id=id).first()

@login_manager.request_loader
def request_loader(request):
    username = request.form.get('username')
    user = User.query.filter_by(username=username).first()
    return user if user else None

app/base/forms.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import InputRequired, Email, DataRequired

## login and registration

class LoginForm(FlaskForm):
    username = TextField    ('Username', id='username_login'   , validators=[DataRequired()])
    password = PasswordField('Password', id='pwd_login'        , validators=[DataRequired()])

class CreateAccountForm(FlaskForm):
    username = TextField('Username'     , id='username_create' , validators=[DataRequired()])
    email    = TextField('Email'        , id='email_create'    , validators=[DataRequired(), Email()])
    password = PasswordField('Password' , id='pwd_create'      , validators=[DataRequired()])

app/base/__init__.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import Blueprint

blueprint = Blueprint(
    'base_blueprint',
    __name__,
    url_prefix='',
    template_folder='templates',
    static_folder='static'
)

app/base/routes.py
# -*- encoding: utf-8 -*-
"""
License: MIT
Copyright (c) 2019 - present AppSeed.us
"""

from flask import jsonify, render_template, redirect, request, url_for
from flask_login import (
    current_user,
    login_required,
    login_user,
    logout_user
)

from app import db, login_manager
from app.base import blueprint
from app.base.forms import LoginForm, CreateAccountForm
from app.base.models import User

from app.base.util import verify_pass

@blueprint.route('/')
def route_default():
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/error-<error>')
def route_errors(error):
    return render_template('errors/{}.html'.format(error))

## Login & Registration

@blueprint.route('/login', methods=['GET', 'POST'])
def login():
    login_form = LoginForm(request.form)
    if 'login' in request.form:
        
        # read form data
        username = request.form['username']
        password = request.form['password']

        # Locate user
        user = User.query.filter_by(username=username).first()
        
        # Check the password
        if user and verify_pass( password, user.password):

            login_user(user)
            return redirect(url_for('base_blueprint.route_default'))

        # Something (user or pass) is not ok
        return render_template( 'login/login.html', msg='Wrong user or password', form=login_form)

    if not current_user.is_authenticated:
        return render_template( 'login/login.html',
                                form=login_form)
    return redirect(url_for('home_blueprint.index'))

@blueprint.route('/create_user', methods=['GET', 'POST'])
def create_user():
    login_form = LoginForm(request.form)
    create_account_form = CreateAccountForm(request.form)
    if 'register' in request.form:

        username  = request.form['username']
        email     = request.form['email'   ]

        user = User.query.filter_by(username=username).first()
        if user:
            return render_template( 'login/register.html', msg='Username already registered', form=create_account_form)

        user = User.query.filter_by(email=email).first()
        if user:
            return render_template( 'login/register.html', msg='Email already registered', form=create_account_form)

        # else we can create the user
        user = User(**request.form)
        db.session.add(user)
        db.session.commit()

        return render_template( 'login/register.html', msg='User created please <a href="/login">login</a>', form=create_account_form)

    else:
        return render_template( 'login/register.html', form=create_account_form)

@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('base_blueprint.login'))

@blueprint.route('/shutdown')
def shutdown():
    func = request.environ.get('werkzeug.server.shutdown')
    if func is None:
        raise RuntimeError('Not running with the Werkzeug Server')
    func()
    return 'Server shutting down...'

## Errors

@login_manager.unauthorized_handler
def unauthorized_handler():
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(403)
def access_forbidden(error):
    return render_template('errors/403.html'), 403

@blueprint.errorhandler(404)
def not_found_error(error):
    return render_template('errors/404.html'), 404

@blueprint.errorhandler(500)
def internal_error(error):
    return render_template('errors/500.html'), 500

app/base/templates/base-site-error.html
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">

    <link rel="icon" href="/static/assets/favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" type="image/x-icon" href="/static/assets/favicon.ico" />
    
    <!-- Generated: 2019-04-04 16:55:45 +0200 -->
    <title>
        Reports Browser - {% block title %}{% endblock %} | WatABot
    </title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">

    <script src="/static/assets/js/require.min.js"></script>
    <script>
      requirejs.config({
          baseUrl: '/static/'
      });
    </script>

    <!-- Dashboard Core -->
    <link href="/static/assets/css/dashboard.css" rel="stylesheet" />
    <script src="/static/assets/js/dashboard.js"></script>
    <!-- c3.js Charts Plugin -->
    <link href="/static/assets/plugins/charts-c3/plugin.css" rel="stylesheet" />
    <script src="/static/assets/plugins/charts-c3/plugin.js"></script>
    <!-- Google Maps Plugin -->
    <link href="/static/assets/plugins/maps-google/plugin.css" rel="stylesheet" />
    <script src="/static/assets/plugins/maps-google/plugin.js"></script>
    <!-- Input Mask Plugin -->
    <script src="/static/assets/plugins/input-mask/plugin.js"></script>
    <!-- Datatables Plugin -->
    <script src="/static/assets/plugins/datatables/plugin.js"></script>

  </head>
<body class="">
    <div class="page">
        <div class="page-content">
            
            {% block content %}{% endblock content %}

        </div>
    </div>
</body>
</html>

app/base/templates/base-site-fullscreen.html
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    
    <link rel="icon" href="/static/assets/favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" type="image/x-icon" href="/static/assets/favicon.ico" />

    <!-- Generated: 2019-04-04 16:55:45 +0200 -->
    <title>
        WatABot - {% block title %}{% endblock %} | CyberBots
    </title>
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">

    <script src="/static/assets/js/require.min.js"></script>
    <script>
      requirejs.config({
          baseUrl: '/static/'
      });
    </script>
    <!-- Dashboard Core -->
    <link href="/static/assets/css/dashboard.css" rel="stylesheet" />
    <script src="/static/assets/js/dashboard.js"></script>
    <!-- c3.js Charts Plugin -->
    <link href="/static/assets/plugins/charts-c3/plugin.css" rel="stylesheet" />
    <script src="/static/assets/plugins/charts-c3/plugin.js"></script>
    <!-- Google Maps Plugin -->
    <link href="/static/assets/plugins/maps-google/plugin.css" rel="stylesheet" />
    <script src="/static/assets/plugins/maps-google/plugin.js"></script>
    <!-- Input Mask Plugin -->
    <script src="/static/assets/plugins/input-mask/plugin.js"></script>
    <!-- Datatables Plugin -->
    <script src="/static/assets/plugins/datatables/plugin.js"></script>

  </head>
  <body class="">
    <div class="page">
      <div class="page-single">
        <div class="container">

          {% block content %}{% endblock content %}

        </div>
      </div>
    </div>

  <!-- Specific Page JS goes HERE  -->
  {% block javascripts %}{% endblock javascripts %}
      
  </body>
</html>

app/base/templates/base-site.html
<!doctype html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">

    <link rel="icon" href="/static/assets/favicon.ico" type="image/x-icon"/>
    <link rel="shortcut icon" type="image/x-icon" href="/static/assets/favicon.ico" />
    
    <!-- Generated: 2019-04-04 16:55:45 +0200 -->
    <title>
        Reports Browser - {% block title %}{% endblock %} | WatABot
    </title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">

    <script src="/static/assets/js/require.min.js"></script>
    <script>
      requirejs.config({
          baseUrl: '/static/'
      });
    </script>

    <!-- Dashboard Core -->
    <link href="/static/assets/css/dashboard.css" rel="stylesheet" />
    <script src="/static/assets/js/dashboard.js"></script>
    <!-- c3.js Charts Plugin -->
    <link href="/static/assets/plugins/charts-c3/plugin.css" rel="stylesheet" />
    <script src="/static/assets/plugins/charts-c3/plugin.js"></script>
    <!-- Google Maps Plugin -->
    <link href="/static/assets/plugins/maps-google/plugin.css" rel="stylesheet" />
    <script src="/static/assets/plugins/maps-google/plugin.js"></script>
    <!-- Input Mask Plugin -->
    <script src="/static/assets/plugins/input-mask/plugin.js"></script>
    <!-- Datatables Plugin -->
    <script src="/static/assets/plugins/datatables/plugin.js"></script>

  </head>
  <body class="">
    <div class="page">
      
      <div class="flex-fill">
        
        {% include 'site_template/top-bar.html' %}

        {% include 'site_template/top-menu.html' %}

        {% block content %}{% endblock content %}

      </div>

      {% include 'site_template/footer.html' %}

    </div>

  <!-- Specific Page JS goes HERE  -->
  {% block javascripts %}{% endblock javascripts %}
      
  </body>
</html>

app/base/templates/login/login.html
{% extends "base-site-fullscreen.html" %}

{% block title %} Login {% endblock %} 

{% block content %}

  <div class="row">
    <div class="col col-login mx-auto">
      <div class="text-center mb-6">
        <img src="/static/assets/demo/logo.png" class="h-6" alt="">
      </div>
      
      <form class="card" action="" method="post">

        {{ form.hidden_tag() }}

        <div class="card-body p-6">
          <div class="card-title text-center">

            {% if msg %}
              {{ msg | safe }}
            {% else %}
            <span>
              Use test credentials: <strong>test / test</strong>
              <br />
              OR <strong><a href={{ url_for('base_blueprint.create_user') }} >create your own user</a></strong>
            </span>
            {% endif %}  
            
          </div>

          <div class="form-group">
            <label class="form-label">Username</label>
            {{ form.username(class="form-control") }}
          </div>
          
          <br />

          <div class="form-group">
            <label class="form-label">
              Password
            </label>
            {{ form.password(class="form-control", type="password") }}
          </div>

          <div class="form-group">
            <label class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" />
              <span class="custom-control-label">Remember me</span>
            </label>
          </div>
          <div class="form-footer">
            <button type="submit" name="login" class="btn btn-primary btn-block">Login</button>
          </div>
        </div>
      </form>
      <div class="text-center text-muted">
        Don't have account yet? <a href={{ url_for('base_blueprint.create_user') }} >Register</a>

        <br />
        <a href="">WatABot</a> - coded by CyberBots Team.
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/login/register.html
{% extends "base-site-fullscreen.html" %}

{% block title %} Register {% endblock %} 

{% block content %}

    <div class="row">
      <div class="col col-login mx-auto">
        <div class="text-center mb-6">
          <img src="/static/assets/demo/logo.png" class="h-6" alt="">
        </div>
        
        <form class="card" action="" method="post">

          {{ form.hidden_tag() }}

          <div class="card-body p-6">
            <div class="card-title text-center">

              {% if msg %}
                {{ msg | safe }}
              {% else %}
                Add your credentials or 
                <strong><a href={{ url_for('base_blueprint.login') }} >authenticate</a></strong> with an existing account.
              {% endif %}  
              
            </div>

            <div class="form-group">
              <label class="form-label">Username</label>
              {{ form.username(class="form-control") }}
            </div>

            <br />
            
            <div class="form-group">
              <label class="form-label">Email</label>
              {{ form.email(class="form-control", type="email") }}
            </div>

            <br />

            <div class="form-group">
              <label class="form-label">
                Password
              </label>
              {{ form.password(class="form-control", type="password") }}
            </div>

            <div class="form-group">
              <label class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" />
                <span class="custom-control-label">Agree the terms</span>
              </label>
            </div>

            <div class="form-footer">
              <button type="submit" name="register" class="btn btn-primary btn-block">Register</button>
            </div>
          </div>
        </form>
        <div class="text-center text-muted">
          Already have account? <a href={{ url_for('base_blueprint.login') }} >Sign IN</a>
          <br />
          <a href="">WatABot</a> - coded by CyberBots Team.
        </div>
      </div>
    </div>
        
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

app/base/templates/site_template/footer.html
      <div class="footer">
          <div class="container">
            <div class="row">
              <div class="col-lg-8">
                <div class="row">
                  <div class="col-6 col-md-3">
                    <ul class="list-unstyled mb-0">
                      <li><a href="index">Home</a></li>
                      <li><a href="https://github.com/WatABot/WatABot">Github</a></li>
                    </ul>
                  </div>
                  <div class="col-6 col-md-3">
                    <ul class="list-unstyled mb-0">
                      <li><a href="#">LinkedIn</a></li>
                      <li><a href="#">Twitter</a></li>
                    </ul>
                  </div>
                  <div class="col-6 col-md-3">
                    <ul class="list-unstyled mb-0">
                      <li><a href="#">Email</a></li>
                      <li><a href="#">WhatsApp</a></li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-lg-4 mt-4 mt-lg-0">
                WatABot: WhatsApp Business bot framework with flask server and Twilio API.
              </div>
            </div>
          </div>
        </div>
        <footer class="footer">
          <div class="container">
            <div class="row align-items-center flex-row-reverse">
              <div class="col-auto ml-lg-auto">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <ul class="list-inline list-inline-dots mb-0">
                      <li class="list-inline-item">
                        &copy; <a href="" target="_blank">WatABot</a> - by CyberBots team.  
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
                <a href="#">WatABot: WhatsApp Bot</a>
              </div>
            </div>
          </div>
        </footer>
  

app/base/templates/site_template/top-bar.html
            <div class="header py-4">
                <div class="container">
                  <div class="d-flex">
                    <a class="header-brand" href="/">
                      <img src="/static/assets/demo/logo.png" class="header-brand-img" alt="tabler logo">
                    </a>
                    <div class="d-flex order-lg-2 ml-auto">
                      <div class="nav-item d-none d-md-flex">
                        <a href="https://github.com/WatABot/WatABot" class="btn btn-sm btn-outline-primary" target="_blank">Github</a>
                      </div>
                      <div class="dropdown d-none d-md-flex">
                        <a class="nav-link icon" data-toggle="dropdown">
                          <i class="fe fe-bell"></i>
                          <span class="nav-unread"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                          <a href="#" class="dropdown-item d-flex">
                            <span class="avatar mr-3 align-self-center" style="background-image: url(/static/assets/demo/faces/male/41.jpg)"></span>
                            <div>
                              <strong>+9398584586</strong> searched from news which is declared as fake.
                              <div class="small text-muted">10 minutes ago</div>
                            </div>
                          </a>
                          <a href="#" class="dropdown-item d-flex">
                            <span class="avatar mr-3 align-self-center" style="background-image: url(/static/assets/demo/faces/female/1.jpg)"></span>
                            <div>
                              <strong>+9052021756</strong> reported fake news.
                              <div class="small text-muted">10 minutes ago</div>
                            </div>
                          </a>
                          <a href="#" class="dropdown-item d-flex">
                            <span class="avatar mr-3 align-self-center" style="background-image: url(/static/assets/demo/faces/female/18.jpg)"></span>
                            <div>
                              <strong>+9398584586</strong> used the bot.
                              <div class="small text-muted">10 minutes ago</div>
                            </div>
                          </a>
                          <div class="dropdown-divider"></div>
                          <a href="#" class="dropdown-item text-center">Mark all as read</a>
                        </div>
                      </div>
                      <div class="dropdown">
                        <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
                          <span class="avatar" style="background-image: url(/static/assets/demo/faces/female/25.jpg)"></span>
                          <span class="ml-2 d-none d-lg-block">
                            <span class="text-default">
                                {{ current_user.username }}
                            </span>
                            <small class="text-muted d-block mt-1">
                                {{ current_user.email }}
                            </small>
                          </span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                          <a class="dropdown-item" href="/page-profile">
                            <i class="dropdown-icon fe fe-user"></i> Profile
                          </a>
                          <div class="dropdown-divider"></div>
                          <a class="dropdown-item" href="#">
                            <i class="dropdown-icon fe fe-help-circle"></i> Support
                          </a>
                          <a class="dropdown-item" href={{ url_for('base_blueprint.logout') }} >
                            <i class="dropdown-icon fe fe-log-out"></i> Sign out
                          </a>
                        </div>
                      </div>
                    </div>
                    <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#headerMenuCollapse">
                      <span class="header-toggler-icon"></span>
                    </a>
                  </div>
                </div>
            </div>

      

app/base/templates/site_template/top-menu.html
            <div class="header collapse d-lg-flex p-0" id="headerMenuCollapse">
                <div class="container">
                  <div class="row align-items-center">
                    <div class="col-lg-3 ml-auto">
                      <form class="input-icon my-3 my-lg-0">
                        <input type="search" class="form-control header-search" placeholder="Search&hellip;" tabindex="1">
                        <div class="input-icon-addon">
                          <i class="fe fe-search"></i>
                        </div>
                      </form>
                    </div>
                    <div class="col-lg order-lg-first">
                      <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
                        <li class="nav-item">
                          <a href="/" class="nav-link active"><i class="fe fe-home"></i> Home</a>
                        </li>
                        <li class="nav-item">
                          <a href="/index#allreports" class="nav-link"><i class="fe fe-calendar"></i> All reports</a>
                        </li>
                        <li class="nav-item dropdown">
                          <a href="/index" class="nav-link"><i class="fe fe-trending-up"></i>Chart Anlysis</a>
                        </li>

                        <li class="nav-item">
                          <a href="/index" class="nav-link"><i class="fe fe-alert-triangle"></i>Fake News</a>
                        </li>

                        <li class="nav-item">
                          <a href="/index" class="nav-link"><i class="fe fe-alert-circle"></i>Suspected Links</a>
                        </li>

                        <!--<li class="nav-item dropdown">
                          <a href="javascript:void(0)" class="nav-link" data-toggle="dropdown"><i class="fe fe-calendar"></i> Components</a>
                          <div class="dropdown-menu dropdown-menu-arrow">
                            <a href="/ui-maps" class="dropdown-item ">Maps</a>
                            <a href="/ui-icons" class="dropdown-item ">Icons</a>
                            <a href="/ui-store" class="dropdown-item ">Store</a>
                            <a href="/ui-blog" class="dropdown-item ">Blog</a>
                            <a href="/ui-carousel" class="dropdown-item ">Carousel</a>
                          </div>
                        </li>
                         <li class="nav-item dropdown">
                          <a href="javascript:void(0)" class="nav-link" data-toggle="dropdown"><i class="fe fe-file"></i> Pages</a>
                          <div class="dropdown-menu dropdown-menu-arrow">
                            <a href="/page-profile" class="dropdown-item ">Profile</a>
                            <a href="/create_user"  class="dropdown-item ">Register</a>
                            <a href="/page-forgot-password" class="dropdown-item ">Forgot password</a>
                            <a href="/page-403"   class="dropdown-item ">403 error</a>
                            <a href="/page-404"   class="dropdown-item ">404 error</a>
                            <a href="/page-500"   class="dropdown-item ">500 error</a>
                            <a href="/page-email" class="dropdown-item ">Email</a>
                            <a href="/page-blank" class="dropdown-item ">Empty page</a>
                            <a href="/page-rtl"   class="dropdown-item ">RTL mode</a>
                          </div>
                        </li> -->

                        <li class="nav-item dropdown">
                          <a href="/ui-form-elements" class="nav-link"><i class="fe fe-check-square"></i>Send Alerts</a>
                        </li>
                        <li class="nav-item">
                          <a href="/team" class="nav-link"><i class="fe fe-image"></i> Team</a>
                        </li>

                      </ul>
                    </div>
                  </div>
                </div>
            </div>
             